version: '3.7'

services:
  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
  php:
    build:
      context: ./
      target: php_dev
    volumes:
      - ./:/srv/api
  nginx:
    build:
      context: ./
      target: base_nginx
    volumes:
      - ./:/srv/api
    ports:
      - 80:80
